config/routes.rb
Rails.application.routes.draw do

  
  resources :events do
resources :pictures
  end
  devise_for :users


namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
    resources :guardian_details
  resources :students
    end
  end

namespace :admins do
    resources :students
    resources :guardian_details
  end

 resources :students
    resources :guardian_details


  root to: 'students#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord

# attr_accessor :firstname, :lastname, :email , :age,:contact, :address, :bloodgroup, :sex, :city, :dob

 has_many :guardian_details,dependent: :destroy ,inverse_of: :student
accepts_nested_attributes_for :guardian_details, reject_if: :all_blank, allow_destroy: true

 validates :firstname, presence: true
 validates :lastname, presence: true
 validates :email, presence: true
 validates :age, presence: true
 validates :contact, presence: true
 validates :address, presence: true
 validates :bloodgroup, presence: true
 validates :sex, presence: true
 validates :city, presence: true
 validates :dob, presence: true


def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end


def self.import(file)
  CSV.foreach(file.path, headers: true) do |row|
    Student.create! row.to_hash
  end
end

end


 

app/controllers/admins/students_controller.rb
class Admins::StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
    respond_to do |format|
      format.html
      format.csv { send_data @students.to_csv }
      format.xls
      format.pdf do
      render :pdf => "students",:template => "students/index"
    end 
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
      @student = Student.find(params[:id])
      respond_to do |format|
    format.html # show.html.erb
    format.pdf do
      render :pdf => "student",:template => "students/show"
    end 
  end
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to admins_student_path(@student), notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to admins_student_path(@student), notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to admins_students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

def import
  Student.import(params[:file])
  redirect_to root_url, notice: "Student imported."
end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:firstname, :lastname, :email, :age, :contact, :address, :bloodgroup, :sex, :city, :dob,guardian_details_attributes: [:id, :name, :contact, :relation, :address, :email, :city, :state, :zipcode, :qualification, :student_id, :_destroy])
    end
end

app/controllers/api/v1/students_controller.rb
module Api
  module V1
    class StudentsController < ApplicationController

       def index
    	@students = Student.all

   		 render json: @students
   
  		end
      
      def show
    render json: @student 
  end
     
     def create
    @student = Student.new(student_params)

    if @student.save
      render json: @student, status: :created, location: @student
    else
      render json: @student.errors, status: :unprocessable_entity
    end
  end

     def update
    if @student.update(student_params)
      render json: @student
    else
      render json: @student.errors, status: :unprocessable_entity
    end
  end

  # DELETE /users/1
  def destroy
    Student.destroy(params[:id])
    @students = Student.all

   		 render json: @students
   

  end

   private
    # Use callbacks to share common setup or constraints between actions.
   def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:firstname, :lastname, :email, :age, :contact, :address, :bloodgroup, :sex, :city,:dob)
    end

    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
    respond_to do |format|
      format.html
      format.csv { send_data @students.to_csv }
      format.xls
      format.pdf do
      render :pdf => "students",:template => "students/index"
    end 
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
      @student = Student.find(params[:id])
      respond_to do |format|
    format.html # show.html.erb
    format.pdf do
      render :pdf => "student",:template => "students/show"
    end 
  end
  end

def import
  Student.import(params[:file])
  redirect_to root_url, notice: "Student imported."
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:firstname, :lastname, :email, :age, :contact, :address, :bloodgroup, :sex, :city, :dob,guardian_details_attributes: [:id, :name, :contact, :relation, :address, :email, :city, :state, :zipcode, :qualification, :student_id, :_destroy])
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/admins/students/_form.html.erb
<%= form_for [:admins, @student], :html => { :class => "form-horizontal student" } do |f| %>

  <% if @student.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @student.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

<div style="width:500px;margin-left: 40px">
  <div class="form-group field" style="width:500px">
    <%= f.label :firstname, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :firstname, :class => 'form-control' %>
    </div>
    <%=f.error_span(:firstname) %>
  </div>
  <div class="form-group field">
    <%= f.label :lastname, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :lastname, :class => 'form-control' %>
    </div>
    <%=f.error_span(:lastname) %>
  </div>
  <div class="form-group field">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group field">
    <%= f.label :age, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :age, :class => 'form-control' %>
    </div>
    <%=f.error_span(:age) %>
  </div>
  <div class="form-group field">
    <%= f.label :contact, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :contact, :class => 'form-control' %>
    </div>
    <%=f.error_span(:contact) %>
  </div>
  <div class="form-group field">
    <%= f.label :address, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :address, :class => 'form-control' %>
    </div>
    <%=f.error_span(:address) %>
  </div>
  <div class="form-group field">
    <%= f.label :bloodgroup, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :bloodgroup, :class => 'form-control' %>
    </div>
    <%=f.error_span(:bloodgroup) %>
  </div>
  <div class="form-group field">
    <%= f.label :sex, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :sex, :class => 'form-control' %>
    </div>
    <%=f.error_span(:sex) %>
  </div>
  <div class="form-group field">
    <%= f.label :city, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
<%= f.text_field :city, :class => 'form-control' %>
    </div>
    <%=f.error_span(:city) %>
  </div>
  <div class="form-group field">
    <%= f.label :dob, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :dob, :class => 'form-control' %>
    </div>
    <%=f.error_span(:dob) %>
  </div>

<h3>
  Guardian
</h3>
<div id="guardian_details">
  <%= f.fields_for :guardian_details do |guardian_detail| %>
  <%= render 'guardian_detail_fields', f: guardian_detail %>
  <% end %>
  <div class="links">
    <%= link_to_add_association 'add GUARDIAN', f, :guardian_details %>
  </div>
</div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admins_students_path, :class => 'btn btn-default' %>
    </div>
  </div>
</div>


<% end %>

app/views/admins/students/_guardian_detail_fields.html.erb
<div class="nested-fields">

	<div class="form-group field">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group field">
    <%= f.label :contact, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :contact, :class => 'form-control' %>
    </div>
    <%=f.error_span(:contact) %>
  </div>
  <div class="form-group field">
    <%= f.label :relation, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :relation, :class => 'form-control' %>
    </div>
    <%=f.error_span(:relation) %>
  </div>
  <div class="form-group field">
    <%= f.label :address, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :address, :class => 'form-control' %>
    </div>
    <%=f.error_span(:address) %>
  </div>
  <div class="form-group field">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group field">
    <%= f.label :city, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :city, :class => 'form-control' %>
    </div>
    <%=f.error_span(:city) %>
  </div>
  <div class="form-group field">
    <%= f.label :state, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :state, :class => 'form-control' %>
    </div>
    <%=f.error_span(:state) %>
  </div>
  <div class="form-group field">
    <%= f.label :zipcode, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :zipcode, :class => 'form-control' %>
    </div>
    <%=f.error_span(:zipcode) %>
  </div>
  <div class="form-group field">
    <%= f.label :qualification, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :qualification, :class => 'form-control' %>
    </div>
    <%=f.error_span(:qualification) %>
  </div>
  <div class="form-group field">
    <%= f.label :student_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
   <%= f.text_field :student_id, :class => 'form-control' %>
</div>
    <%=f.error_span(:student_id) %>
  </div>

<%= link_to_remove_association "remove guardian", f %>	
</div>

app/views/admins/students/edit.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admins/students/index.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:firstname) %></th>
      <th><%= model_class.human_attribute_name(:lastname) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:age) %></th>
      <th><%= model_class.human_attribute_name(:contact) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:bloodgroup) %></th>
      <th><%= model_class.human_attribute_name(:sex) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:dob) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= link_to student.id, student_path(student) %></td>
        <td><%= student.firstname %></td>
        <td><%= student.lastname %></td>
        <td><%= student.email %></td>
        <td><%= student.age %></td>
        <td><%= student.contact %></td>
        <td><%= student.address %></td>
        <td><%= student.bloodgroup %></td>
        <td><%= student.sex %></td>
        <td><%= student.city %></td>
        <td><%= student.dob %></td>
        <td><%=l student.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      admins_student_path(student), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admins_student_path(student), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admins_student_path(student),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admins_student_path,
            :class => 'btn btn-primary' %>

 <%= link_to "CSV", admins_students_path(format: "csv") , :class => 'btn btn-primary' %> |
  <%= link_to "Excel", admins_students_path(format: "xls") , :class => 'btn btn-primary'%>
<%= link_to "Download Invoice (PDF)", students_path(@students, :format => "pdf" , :class => 'btn btn-primary') %>
  

app/views/admins/students/index.pdf.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped table-responsive">
  <thead>
    <tr>
    
      <th><%= model_class.human_attribute_name(:firstname) %></th>
      <th><%= model_class.human_attribute_name(:lastname) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:age) %></th>
      <th><%= model_class.human_attribute_name(:contact) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:bloodgroup) %></th>
      <th><%= model_class.human_attribute_name(:sex) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:dob) %></th>
   
    
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
       
        <td><%= student.firstname %></td>
        <td><%= student.lastname %></td>
        <td><%= student.email %></td>
        <td><%= student.age %></td>
        <td><%= student.contact %></td>
        <td><%= student.address %></td>
        <td><%= student.bloodgroup %></td>
        <td><%= student.sex %></td>
        <td><%= student.city %></td>
        <td><%= student.dob %></td>
       
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admins/students/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">first name</Data></Cell>
        <Cell><Data ss:Type="String">last name</Data></Cell>
        <Cell><Data ss:Type="String">email</Data></Cell>
        <Cell><Data ss:Type="String">age</Data></Cell>
        <Cell><Data ss:Type="String">contact</Data></Cell>
        <Cell><Data ss:Type="String">address</Data></Cell>
        <Cell><Data ss:Type="String">blood group</Data></Cell>
        <Cell><Data ss:Type="String">sex</Data></Cell>
        <Cell><Data ss:Type="String">city</Data></Cell>
        <Cell><Data ss:Type="String">date of birth</Data></Cell>

      </Row>
    <% @students.each do |student| %>
      <Row>
        <Cell><Data ss:Type="String"><%= student.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= student.firstname %></Data></Cell>
        <Cell><Data ss:Type="String"><%= student.lastname %></Data></Cell>
        <Cell><Data ss:Type="String"><%= student.email %></Data></Cell>
        <Cell><Data ss:Type="String"><%= student.age %></Data></Cell>
        <Cell><Data ss:Type="String"><%= student.contact %></Data></Cell>
        <Cell><Data ss:Type="String"><%= student.address %></Data></Cell>
        <Cell><Data ss:Type="String"><%= student.bloodgroup %></Data></Cell>
        <Cell><Data ss:Type="String"><%= student.sex %></Data></Cell>
        <Cell><Data ss:Type="String"><%= student.city %></Data></Cell>
        <Cell><Data ss:Type="String"><%= student.dob %></Data></Cell>

      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/admins/students/new.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admins/students/show.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:firstname) %>:</strong></dt>
  <dd><%= @student.firstname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lastname) %>:</strong></dt>
  <dd><%= @student.lastname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @student.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:age) %>:</strong></dt>
  <dd><%= @student.age %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contact) %>:</strong></dt>
  <dd><%= @student.contact %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @student.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bloodgroup) %>:</strong></dt>
  <dd><%= @student.bloodgroup %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sex) %>:</strong></dt>
  <dd><%= @student.sex %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @student.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:dob) %>:</strong></dt>
  <dd><%= @student.dob %></dd>
</dl>

<div>
<%= link_to t('.back', :default => t("helpers.links.back")),
              admins_students_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admins_student_path(@student), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admins_student_path(@student),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<p id="pdf_link"><%= link_to "Download Invoice (PDF)", admins_student_path(@student, :format => "pdf") %></p>

app/views/admins/students/show.pdf.erb
<%- model_class = Student -%>
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:firstname) %>:</strong></dt>
  <dd><%= @student.firstname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lastname) %>:</strong></dt>
  <dd><%= @student.lastname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @student.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:age) %>:</strong></dt>
  <dd><%= @student.age %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contact) %>:</strong></dt>
  <dd><%= @student.contact %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @student.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bloodgroup) %>:</strong></dt>
  <dd><%= @student.bloodgroup %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sex) %>:</strong></dt>
  <dd><%= @student.sex %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @student.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:dob) %>:</strong></dt>
  <dd><%= @student.dob %></dd>
</dl>